### ISSUE TITLE
Setup subpage on Activate page

### ISSUE THREAD

**Issue by MichaelKohler** [MichaelKohler/activate-impact-form-api#1]
We need to have a subpage on activate.mozilla.community to make people aware of this data as well as to provide good integration with MozActivate.

This repository will only hold the API code, the rest will live on activate.mozilla.community.

**Comment by MichaelKohler** [comment]
@couci does that make sense? Then we should move this issue to the activate repository once we have a decision.

**Comment by MichaelKohler** [comment]
@couci and if that is the case, we probably want to file the user stories in the activate repository as well and we can really just treat this repository here just as a backend.

**Comment by couci** [comment]
Yes let's move this, once this is done I will write the user stories and we can move forward

**Comment by MichaelKohler** [comment]
Actually, if we have the other user stories in the activate story, we don't need a general one. Can you please start to file them in the activate repo?
